### PR TITLE
Add a sleep method in ServiceManager

### PR DESCRIPTION
**Pull request by ICONationDevTeam**
In some test cases we need to sleep during a long period of time.
I'm not sure if the block height increase is good enough or if we should let the user chose the target height.

### CODE REVIEW

**Comment by sink772** [comment]
As I mentioned earlier in https://github.com/icon-project/java-score-examples/issues/2#issuecomment-847437974, `testsvc` module is not intended for that kind of usage. Unit test cases should be finished within a few seconds regardless of how many test cases are there.  If you want to test with automatic block generations, you need to use the integration test.

**Comment by ICONationDevTeam** [comment]
@sink772  Actually, the `ServiceManager.sleep` method implemented in this PR don't really sleep. It only fakes time being passed. With this method, the unit tests don't take any longer.

I can't find a way to mock System.nanoTime() with Mockito, otherwise I would have done that.

Integration tests solve the issue but aren't practical - some features I'm testing need to wait for multiple days.

**Comment by sink772** [comment]
> some features I'm testing need to wait for multiple days.

I'm saying that the above case should not be tested with `unittest`. That kind of tests definitely should be performed on integration tests.

**Comment by ICONationDevTeam** [comment]
I agree but would you have an idea how without waiting for multiple days ? I can't seem to figure it out. Not only I don't see any time travel method implemented, and I can't figure out where it should be implemented if it's not.

Is it really so bad to use time traveling in Unit tests though? Many unit tests frameworks include them

**Comment by sink772** [comment]
What if a contract calls `Context.getBlockTimestamp` multiple times in a method?  There should be no side-effect on the return value. The code you have written breaks the this assumption.

In my case, I wrote the code like the below to mimic the block traveling. I'm not sure if this works for you too though.
https://github.com/icon-project/java-score-examples/blob/ace30a5e1b60cf613bf7b09c7f02e3dddf5a58d1/sample-crowdsale/src/test/java/com/iconloop/score/example/SampleCrowdsaleTest.java#L111

**Comment by ICONationDevTeam** [comment]
> What if a contract calls Context.getBlockTimestamp multiple times in a method

I don't see the issue. The contract would receive the timestamp + sleeptime, as expected. Do you mean from a test to another ? I assume the ServiceManager is reset between each test, otherwise the block height is also a side effect? I believe the PR could be refactored to prevent these side effects if that's the issue.


I have implemented many tests with that custom sleep method successfully, such as this one : 

```py
  void set_new_fee (BigInteger fee, BigInteger admin_fee) {
    commit_new_fee(owner, fee, admin_fee);
    sm.sleep(COMMIT_WAIT.longValue());
    apply_new_fee(owner);
  }
```

Where `commit_new_fee` set the current block timestamp + a delay : 

```py
    @External
    public void commit_new_fee(BigInteger _new_fee, BigInteger _new_admin_fee) {
        // [...]
        BigInteger now = BigInteger.valueOf(Context.getBlockTimestamp());
        BigInteger deadline = now.add(ADMIN_ACTIONS_DELAY);
        this.admin_actions_deadline.set(deadline);
```

And where `apply_new_fee` checks the block timestamp : 

```py
    @External
    public void apply_new_fee() {
        BigInteger now = BigInteger.valueOf(Context.getBlockTimestamp());
        Context.require(now.compareTo(this.admin_actions_deadline.get()) >= 0, 
            "apply_new_fee: now insufficient time");
```

The test passes successfully only with a sufficient sleep time, both in real time and with the "fake sleep" method.


More complicated ones that sleeps + mine blocks in multiple iterations as well : 

```py
    [...]
    while (sm.getBlock().getTimestamp() < future_time.longValue()) {
        sm.sleep(SMALLER_TIME.longValue());
        sm.getBlock().increase();
        BigDecimal nowD = BigDecimal.valueOf(sm.getBlock().getTimestamp());
        BigDecimal ratio = (nowD.subtract(initial_time)).divide(duration, MathContext.DECIMAL128).multiply(new BigDecimal(initial_A));
        BigInteger expected = new BigDecimal(initial_A).add(ratio).toBigInteger();
        
        BigDecimal lower = BigDecimal.valueOf(0.999);
        BigInteger A = (BigInteger) pool.call("A");
        BigDecimal middle = new BigDecimal(expected).divide(new BigDecimal(A), MathContext.DECIMAL128);
        BigDecimal upper = BigDecimal.valueOf(1.0);

        assertTrue(lower.compareTo(middle) < 0);
        assertTrue(middle.compareTo(upper) <= 0);
    }
```

It behaves perfectly imo.

> In my case, I wrote the code like the below to mimic the block traveling. I'm not sure if this works for you too though.

It doesn't unfortunately, I'm looking for time traveling, not block traveling

**Comment by sink772** [comment]
Fixed in icon-project/javaee-unittest@2592b7b3f689e60e73f9c983f5c761761574e5d9

**Pull request closed without merging**
