### PR TITLE
Update IRC2BasicToken.java

### PR DESCRIPTION
**Pull request by ICONationDevTeam**
Use native BigInteger's pow method

### CODE REVIEW

**Comment by sink772** [comment]
First of all, thanks for your interest in this project.

Unfortunately, the `pow` method of `BigInteger` has been excluded from the allowlist of JCL (Java Class Library), because we cannot determine its correct step cost beforehand. That's why I implemented the custom `pow10` method instead of using the default `pow` method.  Thus this PR cannot be accepted.  I hope you understand this situation.

**Comment by ICONationDevTeam** [comment]
No problem at all ! I'm still learning.

Is there a list of banned methods or any 
documentation about the allowlist somewhere in the code please ?

**Comment by sink772** [comment]
I'm preparing a simple tool to show up all the JCL methods that can be used for Java contracts. Please stay tuned! :smile:

**Comment by ICONationDevTeam** [comment]
Awesome thanks !

I've been thinking about adding simple yet useful methods such as pow10 to scorex, does it sound like a good idea to you?

**Comment by sink772** [comment]
The `javaee-scorex` library is primarily intended to be used for drop-in replacement of the standard `java.io` or `java.util` classes, such as `java.util.ArrayList`, that is not in the JCL.  `BigInteger.pow()` is somehat different situation, since its class is already in the JCL but only the method is excluded.  So I do not prefer to include the methods like `pow10` in the `javaee-scorex` library. Maybe you need to provide your own utility methods library.

**Comment by sink772** [comment]
I've added `allowlist` app to the `javaee` module.
https://github.com/icon-project/goloop/commit/06a61c6abad6a34355bf4c4105fc541c9ced2a10
You can run the app using the following command.
```
$ cd <to_your_goloop_root>/javaee
$ ./gradlew app:allowlist:run
```

**Comment by ICONationDevTeam** [comment]
Sounds good about scorex, thanks ! It sounds good. I'll make a separate package for such utility methods.

And thanks a lot about the allowlist, it'll be very useful :) 
I'll close this issue now. Have a nice day!

**Pull request closed without merging**
